#!/bin/sh
# create_project username project_name project

if [ "$#" != 2 ]
then
    echo "Usage: create_project username project_name"
    exit 1
fi

USERNAME=$1
PROJECT=$2.git
GIT_CODE=/data

CODE_PATH=$GIT_CODE/$USERNAME/$PROJECT

# create bare repository
git init --bare $CODE_PATH

# change access rights
chown $USERNAME.$USERNAME -R $CODE_PATH
chmod 700 -R $CODE_PATH
