#!/bin/sh
# create_user username password

if [ "$#" != 2 ]
then
    echo "Usage: create_user username password"
    exit 1
fi

USERNAME=$1
PASSWORD=$2
GIT_CODE=/data

# create user
# useradd -d "/home/$USERNAME" -m -s '/usr/bin/git-shell' $USERNAME
adduser -D -h "/home/$USERNAME" -s '/usr/bin/git-shell' $USERNAME
echo "$USERNAME:$PASSWORD" | chpasswd

# create git repository
mkdir -p $GIT_CODE/$USERNAME

chown $USERNAME.$USERNAME -R $GIT_CODE/$USERNAME
chmod 700 -R $GIT_CODE/$USERNAME
